=== bob-collective/tokenlist/token.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Token Schema",
  "type": "object",
  "definitions": {
    "ChainProperties": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/Name"
        },
        "symbol": {
          "$ref": "#/definitions/Symbol"
        },
        "address": {
          "$ref": "#/definitions/Address"
        },
        "decimals": {
          "$ref": "#/definitions/Decimals"
        },
        "bridge": {
          "type": "object",
          "properties": {
            "bob": {
              "$ref": "#/definitions/Address"
            },
            "bob-sepolia": {
              "$ref": "#/definitions/Address"
            },
            "ethereum": {
              "$ref": "#/definitions/Address"
            },
            "sepolia": {
              "$ref": "#/definitions/Address"
            },
            "bnb-smart-chain": {
              "$ref": "#/definitions/Address"
            },
            "base": {
              "$ref": "#/definitions/Address"
            },
            "op-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "arbitrum-one": {
              "$ref": "#/definitions/Address"
            },
            "polygon": {
              "$ref": "#/definitions/Address"
            },
            "avalanche": {
              "$ref": "#/definitions/Address"
            },
            "unichain": {
              "$ref": "#/definitions/Address"
            },
            "sonic": {
              "$ref": "#/definitions/Address"
            },
            "sei-network": {
              "$ref": "#/definitions/Address"
            },
            "soneium-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "berachain": {
              "$ref": "#/definitions/Address"
            },
            "swellchain": {
              "$ref": "#/definitions/Address"
            },
            "telos": {
              "$ref": "#/definitions/Address"
            }
          }
        },
        "overrides": {
          "type": "object",
          "properties": {
            "name": {
              "$ref": "#/definitions/Name"
            },
            "symbol": {
              "$ref": "#/definitions/Symbol"
            },
            "decimals": {
              "$ref": "#/definitions/Decimals"
            }
          }
        }
      },
      "required": ["address"],
      "additionalProperties": false
    },
    "Decimals": {
      "type": "integer",
      "description": "The number of decimals for the token balance",
      "minimum": 0,
      "maximum": 255,
      "examples": [18]
    },
    "Address": {
      "type": "string",
      "description": "The checksummed address of the token on the specified chain ID",
      "pattern": "^(0x[a-fA-F0-9]{40}|[1-9A-HJ-NP-Za-km-z]{32,44})$",
      "examples": [
        "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "So11111111111111111111111111111111111111112"
      ]
    },
    "Name": {
      "type": "string",
      "description": "The name of the token",
      "minLength": 0,
      "maxLength": 60,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^[ \\S+]+$"
        }
      ],
      "examples": ["USD Coin"]
    },
    "Symbol": {
      "type": "string",
      "description": "The symbol for the token",
      "minLength": 0,
      "maxLength": 20,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^\\S+$"
        }
      ],
      "examples": ["USDC"]
    }
  },
  "properties": {
    "$schema": { "type": "string", "format": "uri-reference" },
    "name": {
      "$ref": "#/definitions/Name"
    },
    "symbol": {
      "$ref": "#/definitions/Symbol"
    },
    "decimals": {
      "$ref": "#/definitions/Decimals"
    },
    "description": {
      "type": "string",
      "description": "A description of the token or project (can be empty)"
    },
    "website": {
      "type": "string",
      "description": "URL of the project's website",
      "format": "uri",
      "pattern": "^https?://.+"
    },
    "twitter": {
      "type": "string",
      "description": "Twitter handle of the project, e.g., '@gobob'",
      "pattern": "^@?[A-Za-z0-9_]+$"
    },
    "tokens": {
      "type": "object",
      "description": "Network-specific token addresses",
      "properties": {
        "bob": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bob-sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "ethereum": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bnb-smart-chain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "base": {
          "$ref": "#/definitions/ChainProperties"
        },
        "op-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "arbitrum-one": {
          "$ref": "#/definitions/ChainProperties"
        },
        "polygon": {
          "$ref": "#/definitions/ChainProperties"
        },
        "avalanche": {
          "$ref": "#/definitions/ChainProperties"
        },
        "unichain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sonic": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sei-network": {
          "$ref": "#/definitions/ChainProperties"
        },
        "soneium-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "berachain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "swellchain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "telos": {
          "$ref": "#/definitions/ChainProperties"
        }
      },
      "minProperties": 1,
      "additionalProperties": false
    }
  },
  "required": ["name", "symbol", "decimals", "tokens"],
  "additionalProperties": false
}

=== bob-collective/tokenlist/data/UNI/data.json
{
  "$schema": "https://raw.githubusercontent.com/bob-collective/tokenlist/refs/heads/main/token.schema.json",
  "name": "Uniswap",
  "symbol": "UNI",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x6fD31f56eb971113bEA12C5883deC68337b3B7b5",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/tokenlist/data/USDC.e/data.json
{
  "$schema": "../../token.schema.json",
  "name": "USD Coin",
  "symbol": "USDC",
  "decimals": 6,
  "description": "USDC is a digital dollar issued by Circle, backed 100% by highly liquid cash and cash-equivalent assets and redeemable 1:1 for USD.",
  "website": "https://www.usdc.com/",
  "twitter": "@circle",
  "tokens": {
    "bob": {
      "name": "Bridged USDC (BOB)",
      "symbol": "USDC.e",
      "address": "0xe75D0fB2C24A55cA1e3F96781a2bCC7bdba058F0",
      "bridge": {
        "ethereum": "0xe497788F8Fcc30B773C9A181a0FFE2e60645cE90"
      },
      "overrides": {
        "name": "Bridged USDC",
        "symbol": "USDC.e"
      }
    },
    "bob-sepolia": {
      "name": "Bridged USDC (BOB)",
      "symbol": "USDC.e",
      "address": "0x2c1f73d37E7cdbA2792156139b0d35A765d595C5",
      "bridge": {
        "sepolia": "0x5C2A45A35ba99d8Ee58c4bB96e2Ce30dA86C530b"
      },
      "overrides": {
        "name": "Bridged USDC",
        "symbol": "USDC.e"
      }
    }
  }
}

=== bob-collective/tokenlist/data/cbBTC/data.json
{
  "$schema": "../../token.schema.json",
  "name": "Coinbase Wrapped BTC",
  "symbol": "cbBTC",
  "decimals": 8,
  "tokens": {
    "ethereum": {
      "address": "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
    },
    "arbitrum-one": {
      "address": "0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf"
    }
  }
}

=== bob-collective/tokenlist/data/STONE/data.json
{
  "$schema": "https://raw.githubusercontent.com/bob-collective/tokenlist/refs/heads/main/token.schema.json",
  "name": "StakeStone Ether",
  "symbol": "STONE",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0x7122985656e38BDC0302Db86685bb972b145bD3C",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x96147A9Ae9a42d7Da551fD2322ca15B71032F342",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/tokenlist/data/sFRAX/data.json
{
  "$schema": "../../token.schema.json",
  "name": "Staked FRAX",
  "symbol": "sFRAX",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0xA663B02CF0a4b149d2aD41910CB81e23e1c41c32",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xb7eae04B995B3b365040dEE99795112ADD43afa0",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/tokenlist/data/uniBTC/data.json
{
  "$schema": "../../token.schema.json",
  "name": "uniBTC",
  "symbol": "uniBTC",
  "decimals": 8,
  "description": "",
  "website": "https://www.bedrock.technology/",
  "twitter": "@Bedrock_DeFi",
  "tokens": {
    "ethereum": {
      "address": "0x004e9c3ef86bc1ca1f0bb5c7662861ee93350568"
    },
    "bob": {
      "address": "0x236f8c0a61dA474dB21B693fB2ea7AAB0c803894"
    },
    "op-mainnet": {
      "address": "0x93919784c523f39cacaa98ee0a9d96c3f32b593e"
    },
    "arbitrum-one": {
      "address": "0x6B2a01A5f79dEb4c2f3c0eDa7b01DF456FbD726a"
    },
    "base": {
      "address": "0x93919784c523f39cacaa98ee0a9d96c3f32b593e"
    },
    "bnb-smart-chain": {
      "address": "0x6b2a01a5f79deb4c2f3c0eda7b01df456fbd726a"
    }
  }
}

=== bob-collective/tokenlist/data/TRB/data.json
{
  "$schema": "https://raw.githubusercontent.com/bob-collective/tokenlist/refs/heads/main/token.schema.json",
  "name": "Tellor Tributes",
  "symbol": "TRB",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0x88df592f8eb5d7bd38bfef7deb0fbc02cf3778a0",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x665060707c3Ea3c31b3eaBaD7F409072446E1D50",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/tokenlist/data/ALEX/data.json
{
  "$schema": "https://raw.githubusercontent.com/bob-collective/tokenlist/refs/heads/main/token.schema.json",
  "name": "ALEX",
  "symbol": "ALEX",
  "decimals": 18,
  "description": "",
  "website": "https://www.alexgo.io/",
  "twitter": "@alexlabBTC",
  "tokens": {
    "ethereum": {
      "address": "0xe7c3755482d0dA522678Af05945062d4427e0923"
    },
    "bob": {
      "address": "0xa669e059fDcbDFC532A2edd658eb2922799EEDb8"
    }
  }
}
