=== bob-collective/tokenlist/token.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Token Schema",
  "type": "object",
  "definitions": {
    "ChainProperties": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/Name"
        },
        "symbol": {
          "$ref": "#/definitions/Symbol"
        },
        "address": {
          "$ref": "#/definitions/Address"
        },
        "decimals": {
          "$ref": "#/definitions/Decimals"
        },
        "bridge": {
          "type": "object",
          "properties": {
            "bob": {
              "$ref": "#/definitions/Address"
            },
            "bob-sepolia": {
              "$ref": "#/definitions/Address"
            },
            "ethereum": {
              "$ref": "#/definitions/Address"
            },
            "sepolia": {
              "$ref": "#/definitions/Address"
            },
            "bnb-smart-chain": {
              "$ref": "#/definitions/Address"
            },
            "base": {
              "$ref": "#/definitions/Address"
            },
            "op-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "arbitrum-one": {
              "$ref": "#/definitions/Address"
            },
            "polygon": {
              "$ref": "#/definitions/Address"
            },
            "avalanche": {
              "$ref": "#/definitions/Address"
            },
            "unichain": {
              "$ref": "#/definitions/Address"
            },
            "sonic": {
              "$ref": "#/definitions/Address"
            },
            "sei-network": {
              "$ref": "#/definitions/Address"
            },
            "soneium-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "berachain": {
              "$ref": "#/definitions/Address"
            },
            "swellchain": {
              "$ref": "#/definitions/Address"
            },
            "telos": {
              "$ref": "#/definitions/Address"
            }
          }
        },
        "overrides": {
          "type": "object",
          "properties": {
            "name": {
              "$ref": "#/definitions/Name"
            },
            "symbol": {
              "$ref": "#/definitions/Symbol"
            },
            "decimals": {
              "$ref": "#/definitions/Decimals"
            }
          }
        }
      },
      "required": ["address"],
      "additionalProperties": false
    },
    "Decimals": {
      "type": "integer",
      "description": "The number of decimals for the token balance",
      "minimum": 0,
      "maximum": 255,
      "examples": [18]
    },
    "Address": {
      "type": "string",
      "description": "The checksummed address of the token on the specified chain ID",
      "pattern": "^(0x[a-fA-F0-9]{40}|[1-9A-HJ-NP-Za-km-z]{32,44})$",
      "examples": [
        "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "So11111111111111111111111111111111111111112"
      ]
    },
    "Name": {
      "type": "string",
      "description": "The name of the token",
      "minLength": 0,
      "maxLength": 60,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^[ \\S+]+$"
        }
      ],
      "examples": ["USD Coin"]
    },
    "Symbol": {
      "type": "string",
      "description": "The symbol for the token",
      "minLength": 0,
      "maxLength": 20,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^\\S+$"
        }
      ],
      "examples": ["USDC"]
    }
  },
  "properties": {
    "$schema": { "type": "string", "format": "uri-reference" },
    "name": {
      "$ref": "#/definitions/Name"
    },
    "symbol": {
      "$ref": "#/definitions/Symbol"
    },
    "decimals": {
      "$ref": "#/definitions/Decimals"
    },
    "description": {
      "type": "string",
      "description": "A description of the token or project (can be empty)"
    },
    "website": {
      "type": "string",
      "description": "URL of the project's website",
      "format": "uri",
      "pattern": "^https?://.+"
    },
    "twitter": {
      "type": "string",
      "description": "Twitter handle of the project, e.g., '@gobob'",
      "pattern": "^@?[A-Za-z0-9_]+$"
    },
    "tokens": {
      "type": "object",
      "description": "Network-specific token addresses",
      "properties": {
        "bob": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bob-sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "ethereum": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bnb-smart-chain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "base": {
          "$ref": "#/definitions/ChainProperties"
        },
        "op-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "arbitrum-one": {
          "$ref": "#/definitions/ChainProperties"
        },
        "polygon": {
          "$ref": "#/definitions/ChainProperties"
        },
        "avalanche": {
          "$ref": "#/definitions/ChainProperties"
        },
        "unichain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sonic": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sei-network": {
          "$ref": "#/definitions/ChainProperties"
        },
        "soneium-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "berachain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "swellchain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "telos": {
          "$ref": "#/definitions/ChainProperties"
        }
      },
      "minProperties": 1,
      "additionalProperties": false
    }
  },
  "required": ["name", "symbol", "decimals", "tokens"],
  "additionalProperties": false
}

=== bob-collective/tokenlist/data/DAI/data.json
{
  "name": "Dai Stablecoin",
  "symbol": "DAI",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x6c851F501a3F24E29A8E39a29591cddf09369080",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "polygon": {
      "name": "(PoS) Dai Stablecoin",
      "address": "0x8f3cf7ad23cd3cadbd9735aff958023239c6a063"
    },
    "arbitrum-one": {
      "address": "0xda10009cbd5d07dd0cecc66161fc93d7c9000da1"
    },
    "bnb-smart-chain": {
      "name": "Dai Token",
      "address": "0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3"
    },
    "op-mainnet": {
      "address": "0xda10009cbd5d07dd0cecc66161fc93d7c9000da1"
    },
    "base": {
      "address": "0x50c5725949a6f0c72e6c4a641f24049a917db0cb"
    }
  }
}

=== bob-collective/tokenlist/data/SolvBTC.JUP/data.json
{
  "$schema": "../../token.schema.json",
  "name": "SolvBTC Jupiter",
  "symbol": "SolvBTC.JUP",
  "decimals": 18,
  "description": "SolvBTC is a yield-bearing Bitcoin asset from Solv Protocol. This version is for the Jupiter platform.",
  "website": "https://app.solv.finance/",
  "twitter": "@SolvProtocol",
  "tokens": {
    "bob": {
      "address": "0x6b062AA7F5FC52b530Cb13967aE2E6bc0D8Dd3E4"
    }
  }
}

=== bob-collective/tokenlist/data/WETH/data.json
{
  "$schema": "https://raw.githubusercontent.com/bob-collective/tokenlist/refs/heads/main/token.schema.json",
  "name": "Wrapped Ether",
  "symbol": "WETH",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "sepolia": {
      "address": "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9"
    },
    "bob": {
      "address": "0x4200000000000000000000000000000000000006",
      "bridge": { "ethereum": "0x4200000000000000000000000000000000000010" }
    },
    "bob-sepolia": {
      "address": "0x4200000000000000000000000000000000000006"
    }
  }
}

=== bob-collective/tokenlist/data/xSolvBTC/data.json
{
  "$schema": "../../token.schema.json",
  "name": "xSolvBTC",
  "symbol": "xSolvBTC",
  "decimals": 18,
  "description": "",
  "website": "https://app.solv.finance/",
  "twitter": "@SolvProtocol",
  "tokens": {
    "ethereum": {
      "address": "0xd9D920AA40f578ab794426F5C90F6C731D159DEf"
    },
    "bob": {
      "address": "0xCC0966D8418d412c599A6421b760a847eB169A8c"
    },
    "bnb-smart-chain": {
      "address": "0x1346b618dc92810ec74163e4c27004c921d446a5"
    },
    "avalanche": {
      "address": "0xcc0966d8418d412c599a6421b760a847eb169a8c"
    },
    "base": {
      "address": "0xc26c9099bd3789107888c35bb41178079b282561"
    },
    "arbitrum-one": {
      "address": "0x346c574c56e1a4aaa8dc88cda8f7eb12b39947ab"
    },
    "polygon": {
      "address": "0xc99f5c922dae05b6e2ff83463ce705ef7c91f077"
    }
  }
}

=== bob-collective/tokenlist/data/BOB/data.json
{
  "$schema": "../../token.schema.json",
  "name": "BOB",
  "symbol": "BOB",
  "decimals": 18,
  "description": "",
  "website": "https://app.gobob.xyz/",
  "twitter": "@build_on_bob",
  "tokens": {
    "ethereum": {
      "address": "0xC9746F73cC33a36c2cD55b8aEFD732586946Cedd",
      "bridge": {
        "bob": "0x80226fc0Ee2b096224EeAc085Bb9a8cba1146f7D",
        "bnb-smart-chain": "0x80226fc0Ee2b096224EeAc085Bb9a8cba1146f7D"
      }
    },
    "bob": {
      "address": "0xb0bd54846a92b214c04a63b26ad7dc5e19a60808",
      "bridge": {
        "ethereum": "0x827716e74F769AB7b6bb374A29235d9c2156932C",
        "bnb-smart-chain": "0x827716e74F769AB7b6bb374A29235d9c2156932C"
      }
    },
    "bob-sepolia": {
      "address": "0x49D6FBFa3Ee5462626D65Cd22FC0CFb03ed907DB"
    },
    "bnb-smart-chain": {
      "address": "0x52B5fB4B0F6572B8C44d0251Cc224513ac5eB7E7",
      "bridge": {
        "ethereum": "0x34B03Cb9086d7D758AC55af71584F81A598759FE",
        "bob": "0x34B03Cb9086d7D758AC55af71584F81A598759FE"
      }
    }
  }
}

=== bob-collective/tokenlist/data/LBTC/data.json
{
  "$schema": "https://raw.githubusercontent.com/bob-collective/tokenlist/refs/heads/main/token.schema.json",
  "name": "Lombard Staked Bitcoin",
  "symbol": "LBTC",
  "decimals": 8,
  "description": "",
  "website": "https://lombard.finance",
  "twitter": "@lombard_finance",
  "tokens": {
    "ethereum": {
      "address": "0x8236a87084f8B84306f72007F36F2618A5634494",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xA45d4121b3D47719FF57a947A9d961539Ba33204",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "bnb-smart-chain": {
      "address": "0xecac9c5f704e954931349da37f60e39f515c11c1"
    },
    "base": {
      "address": "0xecac9c5f704e954931349da37f60e39f515c11c1"
    }
  }
}

=== bob-collective/tokenlist/data/rETH/data.json
{
  "$schema": "../../token.schema.json",
  "name": "Rocket Pool ETH",
  "symbol": "rETH",
  "decimals": 18,
  "website": "https://rocketpool.net/",
  "twitter": "@Rocket_Pool",
  "tokens": {
    "ethereum": {
      "address": "0xae78736cd615f374d3085123a210448e74fc6393",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xB5686c4f60904Ec2BDA6277d6FE1F7cAa8D1b41a",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/tokenlist/data/FBTC/data.json
{
  "$schema": "https://raw.githubusercontent.com/bob-collective/tokenlist/refs/heads/main/token.schema.json",
  "name": "Fire Bitcoin",
  "symbol": "FBTC",
  "decimals": 8,
  "tokens": {
    "ethereum": {
      "address": "0xC96dE26018A54D51c097160568752c4E3BD6C364",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xC96dE26018A54D51c097160568752c4E3BD6C364",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "base": {
      "address": "0xc96de26018a54d51c097160568752c4e3bd6c364"
    },
    "bnb-smart-chain": {
      "address": "0xc96de26018a54d51c097160568752c4e3bd6c364"
    },
    "arbitrum-one": {
      "address": "0xc96de26018a54d51c097160568752c4e3bd6c364"
    }
  }
}
